os:
  - linux
  - windows

language: node_js
node_js:
  # - '12'  Not support until https://github.com/node-ffi/node-ffi/pull/544 solved
  - '11'
  - '10'

cache:
  directories:
    - node_modules

# https://travis-ci.community/t/using-cl-exe-for-32-and-64-bits/1905/4
before_script:
  - /c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat
  - cl.exe //D_USRDLL //D_WINDLL "tests/fixtures/library/factorial.c" //link //DLL //OUT:"tests/fixtures/library/libfactorial.dll"
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y visualstudio2017community visualstudio2017-workload-nativecrossplat; fi
  # - if [ "$TRAVIS_OS_NAME" == 'windows' ]; cl.exe /D_USRDLL /D_WINDLL tests/fixtures/library/factorial.c /link /DLL /OUT:tests/fixtures/library/libfactorial.dll ; fi

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - echo "Testing started ..."
  - npm test

stages:
  - test
  - pack
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

jobs:
  include:
    - stage: pack
      script:
        - ./scripts/generate-version.sh
        - npm run test:pack && echo 'Npm pack testing is passed'

    - stage: deploy
      script:
        - echo "Deploying to NPM ..."
        - npm version
        - ./scripts/generate-version.sh
        - ./scripts/package-publish-config-tag.sh
        - npm run dist

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  email:
    on_success: change
    on_failure: change

